### ISSUE TITLE
debug模式启动febs-server下新增的模块后，停掉或者重启该模块时总是报错

### ISSUE THREAD

**Issue by 4pxzhou** [febsteam/FEBS-Cloud#22]
### 问题描述
简单描述下遇到的问题
RT：按照之前参考文档提示的方式新增的模块，可以成功运行。但是停止或者重启时总是报如下错误： Error creating bean with name 'registrationListener': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
### 复现步骤
简单描述下问题复现的步骤
按照之前参考文档提示的方式新增的模块，可以成功运行。但是停止或者重启时总是报如下错误： 
Error creating bean with name 'registrationListener': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)： 

非debug模式启动后，重启或停止没有该问题

重新添加新模块尝试重现，但是很奇怪原来有问题的模块没有问题了，新增的模块却出现了这个问题。
神奇啊，到底什么原因呢？
### 相关截图
提供相关截图，以协助问题分析
提供完整错误日志如下：
Disconnected from the target VM, address: '127.0.0.1:5444', transport: 'socket'
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler Shutting down ExecutorService
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.alibaba.cloud.nacos.registry.NacosServiceRegistry De-registering from Nacos Server now...
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.alibaba.nacos.client.naming [BEAT] removing beat: DEFAULT_GROUP@@FEBS-Server-App:192.168.0.101:8203 from beat map.
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.alibaba.nacos.client.naming [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@FEBS-Server-App with instance: {"clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"instanceIdGenerator":"simple","ip":"192.168.0.101","ipDeleteTimeout":30000,"metadata":{},"port":8203,"weight":1.0}
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.alibaba.cloud.nacos.registry.NacosServiceRegistry De-registration finished.
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor Shutting down ExecutorService 'febsAsyncThreadPool'
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.codingapi.txlcn.txmsg.netty.impl.NettyRpcServerInitializer server was down.
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer RPC client was down.
2020-06-17 20:47:31 ERROR FEBS-Server-App nioEventLoopGroup-3-1 com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler keepSize:2,nowSize:1
2020-06-17 20:47:31 ERROR FEBS-Server-App nioEventLoopGroup-3-2 com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler keepSize:2,nowSize:1
2020-06-17 20:47:31 ERROR FEBS-Server-App nioEventLoopGroup-3-1 com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler socketAddress:/192.168.0.101:8888 
2020-06-17 20:47:31 INFO  FEBS-Server-App nioEventLoopGroup-3-1 com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer Try connect socket(/192.168.0.101:8888) - count 1
2020-06-17 20:47:31 ERROR FEBS-Server-App nioEventLoopGroup-3-2 com.codingapi.txlcn.txmsg.netty.handler.NettyClientRetryHandler socketAddress:/0.0.0.0:8888 
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.zaxxer.hikari.HikariDataSource HikariPool-1 - Shutdown initiated...
2020-06-17 20:47:31 WARN  FEBS-Server-App nioEventLoopGroup-3-1 com.codingapi.txlcn.txmsg.netty.impl.NettyRpcClientInitializer Connect socket(/192.168.0.101:8888) fail. 6000ms latter try again.
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.zaxxer.hikari.HikariDataSource HikariPool-1 - Shutdown completed.
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.codingapi.txlcn.tc.corelog.H2DbHelper log hikariDataSource close.
2020-06-17 20:47:31 WARN  FEBS-Server-App SpringContextShutdownHook org.springframework.context.annotation.AnnotationConfigApplicationContext Exception thrown from ApplicationListener handling ContextClosedEvent
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'registrationListener': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:212)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.getTargetBean(ApplicationListenerMethodAdapter.java:332)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:297)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:410)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1013)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:979)
	at org.springframework.cloud.context.named.NamedContextFactory.destroy(NamedContextFactory.java:92)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:258)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:579)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:551)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1089)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:512)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1082)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1061)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1030)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949)
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.baomidou.dynamic.datasource.DynamicRoutingDataSource dynamic-datasource start closing ....
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.zaxxer.hikari.HikariDataSource base - Shutdown initiated...
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.zaxxer.hikari.HikariDataSource base - Shutdown completed.
2020-06-17 20:47:31 INFO  FEBS-Server-App SpringContextShutdownHook com.baomidou.dynamic.datasource.DynamicRoutingDataSource dynamic-datasource all closed success,bye

> issue模板，by MrBird.

**Comment by 4pxzhou** [comment]
问题原因已经找到，是因为在工程中加入了Vo，一般来说是不会有问题的，感觉问题出在了lombok上。去掉vo上的lombok注解，一切恢复正常。可能需要一些jar包依赖吧，或者lombok还不太成熟。
